[features]
seeds = false
skip-lint = false
[programs.localnet]
metacamp_anchor = "EWXRk2T8mP9aPtqFYJhC2F2paQ3mUZJRTB6EFH6UQXt4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/lovshains/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
